[package]
name = "fractal"
version = "0.1.0"
edition = "2021"

[lib]
name = "mandelbrot"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
num-complex = "0.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
