name: Deploy to github.io site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Rust output
      id: rust-cache
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-target

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node_version: 18
        cache: 'yarn'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.4.0

    - name: Build Rust project
      run: cargo build -r --verbose

    - name: Build wasm library
      run: |
        cd web
        yarn install --frozen-lockfile
        yarn build:web

    - name: Build React site
      run: |
        cd client
        yarn install --frozen-lockfile
        yarn build

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.7
      with:
        path: client/build

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.0
