[package]
name = "mandelbrot-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fractal = { path = "../fractal" }
wasm-bindgen = "0.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
